import {
  BIDI_CONTROL_RANGES,
  DEFAULT_IGNORABLE_RANGES,
  RGI_EMOJI_TAG_SEQUENCES,
  UNICODE_VERSION,
} from './unicode-data.mjs';

export { UNICODE_VERSION };
export const POLICIES = Object.freeze(['transport', 'preserve']);

const PROTECTED_DEFAULT_IGNORABLE_RANGES = [
  [0x00ad, 0x00ad], [0x034f, 0x034f], [0x061c, 0x061c], [0x115f, 0x1160], [0x17b4, 0x17b5], [0x180b, 0x180f],
  [0x200c, 0x200f], [0x202a, 0x202e], [0x2061, 0x2064], [0x2066, 0x206f], [0x3164, 0x3164], [0xfe00, 0xfe0f],
  [0xffa0, 0xffa0], [0x1bca0, 0x1bca3], [0x1d173, 0x1d17a], [0xe0100, 0xe01ef],
];
const RESERVED_DEFAULT_IGNORABLE_RANGES = [[0x2065,0x2065],[0xfff0,0xfff8],[0xe0000,0xe0000],[0xe0002,0xe001f],[0xe0080,0xe00ff],[0xe01f0,0xe0fff]];
const TAG_RANGES = [[0xe0001,0xe0001],[0xe0020,0xe007f]];
const SPECIAL_NAMES = new Map([[0x0000,'NULL'],[0x00ad,'SOFT HYPHEN'],[0x034f,'COMBINING GRAPHEME JOINER'],[0x061c,'ARABIC LETTER MARK'],[0x180e,'MONGOLIAN VOWEL SEPARATOR'],[0x200b,'ZERO WIDTH SPACE'],[0x200c,'ZERO WIDTH NON-JOINER'],[0x200d,'ZERO WIDTH JOINER'],[0x200e,'LEFT-TO-RIGHT MARK'],[0x200f,'RIGHT-TO-LEFT MARK'],[0x202a,'LEFT-TO-RIGHT EMBEDDING'],[0x202b,'RIGHT-TO-LEFT EMBEDDING'],[0x202c,'POP DIRECTIONAL FORMATTING'],[0x202d,'LEFT-TO-RIGHT OVERRIDE'],[0x202e,'RIGHT-TO-LEFT OVERRIDE'],[0x2060,'WORD JOINER'],[0x2061,'FUNCTION APPLICATION'],[0x2062,'INVISIBLE TIMES'],[0x2063,'INVISIBLE SEPARATOR'],[0x2064,'INVISIBLE PLUS'],[0x2066,'LEFT-TO-RIGHT ISOLATE'],[0x2067,'RIGHT-TO-LEFT ISOLATE'],[0x2068,'FIRST STRONG ISOLATE'],[0x2069,'POP DIRECTIONAL ISOLATE'],[0xfeff,'ZERO WIDTH NO-BREAK SPACE / BOM'],[0xe0001,'LANGUAGE TAG'],[0xe007f,'CANCEL TAG']]);

function inRanges(codePoint,ranges){let low=0,high=ranges.length-1;while(low<=high){const mid=(low+high)>>1,[start,end]=ranges[mid];if(codePoint<start)high=mid-1;else if(codePoint>end)low=mid+1;else return true;}return false;}
export function isDefaultIgnorable(codePoint){return inRanges(codePoint,DEFAULT_IGNORABLE_RANGES);}
export function isBidiControl(codePoint){return inRanges(codePoint,BIDI_CONTROL_RANGES);}
function isAsciiOrC1Control(cp){if(cp===9||cp===10||cp===13)return false;return(cp>=0&&cp<=31)||(cp>=127&&cp<=159);}
function isNoncharacter(cp){return(cp>=0xfdd0&&cp<=0xfdef)||(cp<=0x10ffff&&(cp&0xffff)>=0xfffe);}
function isSurrogate(cp){return cp>=0xd800&&cp<=0xdfff;}
function cpLabel(cp){return `U+${cp.toString(16).toUpperCase().padStart(cp<=0xffff?4:6,'0')}`;}
function nameFor(cp){if(SPECIAL_NAMES.has(cp))return SPECIAL_NAMES.get(cp);if(cp>=0xfe00&&cp<=0xfe0f)return `VARIATION SELECTOR-${cp-0xfe00+1}`;if(cp>=0xe0100&&cp<=0xe01ef)return `VARIATION SELECTOR-${cp-0xe0100+17}`;if(cp>=0xe0020&&cp<=0xe007e)return `TAG ${String.fromCodePoint(cp-0xe0000)}`;return null;}
function recordsFor(text){const records=[];let cpOffset=0,utf16Offset=0,utf8Offset=0;for(const char of text){const codePoint=char.codePointAt(0),utf16Length=char.length,utf8Length=Buffer.byteLength(char,'utf8');records.push({char,codePoint,cpOffset,utf16Offset,utf8Offset,utf16Length,utf8Length});cpOffset++;utf16Offset+=utf16Length;utf8Offset+=utf8Length;}return records;}
function validEmojiTagPositions(records){const valid=new Set();for(let i=0;i<records.length;i++){if(records[i].codePoint!==0x1f3f4)continue;for(const sequence of RGI_EMOJI_TAG_SEQUENCES){if(sequence.length>records.length-i)continue;let matches=true;for(let j=0;j<sequence.length;j++)if(records[i+j].codePoint!==sequence[j]){matches=false;break;}if(matches)for(let j=1;j<sequence.length;j++)valid.add(i+j);}}return valid;}
function removalDecision(record,policy,validTags){const cp=record.codePoint;if(cp===0){return policy==='transport'?{remove:true,kind:'control',reason:'NUL has no text glyph and is unsafe in many text transports.'}:{remove:false,kind:'control',reason:'NUL detected; preserve policy makes no changes.'};}if(!isDefaultIgnorable(cp))return{remove:false};if(validTags.has(record.cpOffset))return{remove:false,kind:'emoji-tag',reason:'Part of a Unicode RGI emoji tag sequence; preserved.'};if(cp===0xfeff&&record.cpOffset===0&&policy==='transport')return{remove:true,kind:'bom',reason:'Leading BOM represented as a text code point; transport policy removes it.'};if(isBidiControl(cp))return{remove:false,kind:'bidi-control',reason:'Invisible bidi control can change visual ordering; always preserved and reported.'};if(inRanges(cp,PROTECTED_DEFAULT_IGNORABLE_RANGES))return{remove:false,kind:'semantic-format',reason:'Invisible but can affect shaping, grapheme behavior, math semantics, or rendering; preserved.'};if(inRanges(cp,TAG_RANGES))return{remove:false,kind:'tag-data',reason:'Unicode tag data detected outside a valid RGI emoji tag sequence; reported but not removed.'};if(inRanges(cp,RESERVED_DEFAULT_IGNORABLE_RANGES))return{remove:false,kind:'reserved-ignorable',reason:'Reserved default-ignorable code point detected; reported but not removed.'};if(cp===0x200b||cp===0x2060||cp===0xfeff)return{remove:false,kind:'zero-width',reason:'Zero-width formatting detected; reported but preserved.'};return{remove:false,kind:'default-ignorable',reason:'Default-ignorable code point detected; reported but preserved.'};}
function findingFor(record,policy,validTags){const decision=removalDecision(record,policy,validTags),cp=record.codePoint,base={codePoint:cp,code:cpLabel(cp),name:nameFor(cp),offsetCodePoint:record.cpOffset,offsetUtf16:record.utf16Offset,offsetUtf8:record.utf8Offset};if(decision.kind)return{...base,kind:decision.kind,action:decision.remove?'remove':'preserve',reason:decision.reason};if(isAsciiOrC1Control(cp))return{...base,kind:'control',action:'preserve',reason:'Control character detected; preserved because some plain-text workflows intentionally use controls.'};if(isNoncharacter(cp))return{...base,name:null,kind:'noncharacter',action:'preserve',reason:'Unicode noncharacter detected; preserved to avoid changing application sentinel data.'};if(isSurrogate(cp))return{...base,name:null,kind:'invalid-scalar',action:'preserve',reason:'Unpaired UTF-16 surrogate detected in the JavaScript string.'};return null;}
export function cleanText(text,{policy='transport'}={}){if(typeof text!=='string')throw new TypeError('text must be a string');if(!POLICIES.includes(policy))throw new RangeError(`Unknown policy: ${policy}. Expected one of: ${POLICIES.join(', ')}`);const records=recordsFor(text),validTags=validEmojiTagPositions(records),findings=[],output=[],removedOffsets=new Set();for(const record of records){const finding=findingFor(record,policy,validTags);if(finding){findings.push(finding);if(finding.action==='remove'){removedOffsets.add(record.cpOffset);continue;}}output.push(record.char);}const cleaned=output.join(''),expected=records.filter(r=>!removedOffsets.has(r.cpOffset)).map(r=>r.char).join('');if(expected!==cleaned)throw new Error('Internal invariant failure: output was not deletion-only.');return{text:cleaned,policy,unicodeVersion:UNICODE_VERSION,changed:cleaned!==text,findings,removed:findings.filter(f=>f.action==='remove'),preservedFindings:findings.filter(f=>f.action==='preserve'),inputCodePoints:records.length,outputCodePoints:records.length-removedOffsets.size,deletionOnly:true};}
export function scanText(text,options={}){return cleanText(text,options);}
export function verifyDeletionOnly(original,cleaned,findings){const removals=new Set((findings??[]).filter(f=>f.action==='remove').map(f=>f.offsetCodePoint)),records=recordsFor(original),expected=records.filter(r=>!removals.has(r.cpOffset)).map(r=>r.char).join('');return expected===cleaned;}
